config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :challenges, only: [:index, :show] do
    resources :chats, only: [:create]
  end

  resources :chats, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  validates :name, :module, :content, presence: true
  has_many :chats, dependent: :destroy
  has_many :messages, through: :chats
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  has_many :messages, dependent: :destroy

  DEFAULT_TITLE = "Untitled"
  TITLE_PROMPT = <<~PROMPT
    Generate a short, descriptive, 3-to-6-word title that summarizes the user question for a chat conversation.
  PROMPT

  def generate_title_from_first_message
    return unless title == DEFAULT_TITLE

    first_user_message = messages.where(role: "user").order(:created_at).first
    return if first_user_message.nil?

    response = RubyLLM.chat.with_instructions(TITLE_PROMPT).ask(first_user_message.content)
    update(title: response.content)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
    # render 'index.html.erb'
    # respond_to do |format|
    #   format.html { render 'index' }
    #   format.json { render json: @challenges }
    #   format.txt { render plain: @challenges }
    # end
  end

  def show
    @challenge = Challenge.find(params[:id])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    @challenge = Challenge.find(params[:challenge_id])

    @chat = Chat.new(title: Chat::DEFAULT_TITLE)
    @chat.challenge = @challenge
    @chat.user = current_user

    if @chat.save
      redirect_to chat_path(@chat)
    else
      render "challenges/show"
    end
  end

  def show
    @chat = current_user.chats.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  SYSTEM_PROMPT = "You are a Teaching Assistant.\n\nI am a student at the Le Wagon AI Software Development Bootcamp, learning how to code.\n\nHelp me break down my problem into small, actionable steps, without giving away solutions.\n\nAnswer concisely in Markdown."

  def create
    @chat = current_user.chats.find(params[:chat_id])
    @challenge = @chat.challenge
    @message = Message.new(message_params)
    @message.chat = @chat
    @message.role = "user"

    if @message.save
      @ruby_llm_chat = RubyLLM.chat
      # give the ruby_llm_chat the history of our conversation
      build_conversation_history
      response = @ruby_llm_chat.with_instructions(instructions).ask(@message.content)
      Message.create(role: "assistant", content: response.content, chat: @chat)
      @chat.generate_title_from_first_message

      # redirect_to chat_messages_path(@chat)
      # stay on the page, display the two new messages only
      # find the messages div
      # insert the last two messages into that
      # render create.turbo_stream.erb
      respond_to do |format|
        format.html { redirect_to chat_messages_path(@chat) }
        format.turbo_stream { render 'create' }
      end
    else
      render "chats/show", status: :unprocessable_entity
    end
  end

  private

  def build_conversation_history
    @chat.messages.each do |message|
      @ruby_llm_chat.add_message(message)
    end
  end

  # system prompt, challenge context + message i sent (send the chat history)
  def instructions
    challenge_context = "Here is the context of the challenge: #{@challenge.content}."
    [SYSTEM_PROMPT, challenge_context, @challenge.system_prompt].compact.join("\n\n")
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @challenges = Challenge.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    Kramdown::Document.new(text, input: 'GFM', syntax_highlighter: "rouge").to_html
  end
end

app/views/challenges/index.html.erb
<div class="container">
  <h1>Challenges</h1>
  <ul>
    <% @challenges.each do |challenge| %>
      <li><%= link_to challenge.name, challenge_path(challenge) %></li>
    <% end %>
  </ul>
</div>

app/views/challenges/show.html.erb
<div class="row">
  <div class="col">
    <h1><%= @challenge.name %></h1>
    <%= raw(render_markdown(@challenge.content)) %>
  </div>
  <div class="col-md-3">
    <h2>Chats</h2>
    <div class="mb-4">
      <% if @challenge.chats.any? %>
        <ul>
          <% @challenge.chats.each do |chat| %>
            <li><%= link_to chat.title, chat_path(chat) %></li>
          <% end %>
        </ul>
      <% else %>
        There are no chats yet.
      <% end %>
    </div>
    <%= button_to "New chat", challenge_chats_path(@challenge), class: "btn btn-primary" %>
  </div>
</div>

app/views/chats/show.html.erb
<%= link_to "← #{@chat.challenge.name}", challenge_path(@chat.challenge) %>
<h1 id="chat_title"><%= @chat.title %></h1>
<div id="messages">
  <%= render 'messages/messages', messages: @chat.messages %>
</div>
<div id="new_message_container">
  <%# The keys inside of a render statement, are variables inside of that partials %>
  <%= render 'messages/form', chat: @chat, message: @message %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAiChallenges</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container my-4">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%# these variables were set in the render %>
<%= simple_form_for [chat, message] do |f| %>
  <%= f.input :content, label: "Ask a question", required: true, placeholder: "How should I get started with the challenge?" %>
  <%= f.button :submit, 'Ask LLM', class: 'btn btn-primary' %>
<% end %>

app/views/messages/_messages.html.erb
<% messages.each do |message| %>
  <% if message.role == "user" %>
    <div class="d-flex justify-content-end mb-2">
      <div class="bg-white px-3 pb-0 pt-3 rounded-pill">
        <%= raw(render_markdown(message.content)) %>
      </div>
    </div>
  <% elsif message.role == "assistant" %>
    <div class="d-flex justify-content-start mb-5">
      <div class="px-3 pb-0 pt-3">
        <%= raw(render_markdown(message.content)) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/messages/create.turbo_stream.erb
<%# # find the messages div
      # insert the last two messages into that %>
<%# turbo_stream.verb 'id_of_location' %>
<%= turbo_stream.append "messages" do %>
  <%# insert an HTML partial %>
  <%= render 'messages/messages', messages: @chat.messages.order(created_at: :asc).last(2) %>
<% end %>
<%= turbo_stream.update "new_message_container" do %>
  <%= render 'messages/form', chat: @chat, message: Message.new %>
<% end %>

app/views/pages/home.html.erb
<div class="container">
  <h1>Challenges</h1>
  <ul>
    <% @challenges.each do |challenge| %>
      <li><%= link_to challenge.name, challenge_path(challenge) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://octodex.github.com/images/Robotocat.png", class: 'rounded' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Challenges", challenges_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/dmbf29", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>